name: CI test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  MergeTest:
    runs-on: ubuntu-20.04

    steps:
      - name: LNST upstream checkout
        uses: actions/checkout@v2
        with:
          repository: LNST-project/lnst
          path: upstream
          ref: master

      - name: Source checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Test
        run: |
          git remote add upstream "../upstream/"
          git fetch upstream master
          git branch
          git remote show
          git log -n 2
          git rebase upstream/master
          git log -n 2
