name: CI test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  MergeTest:
    runs-on: ubuntu-20.04

    steps:
      - name: LNST upstream checkout
        uses: actions/checkout@v2
        with:
          path: lnst-upstream
          repository: LNST-project/lnst
          ref: master

      - name: Source checkout
        uses: actions/checkout@v2
        with:
          path: lnst
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Test
        run: |
          cd "$GITHUB_WORKSPACE"/lnst
          git remote add upstream "$GITHUB_WORKSPACE/lnst-upstream"
          git fetch --unshallow upstream
          git config --local user.email "lnst-developers@lists.fedorahosted.org"
          git config --local user.name "LNST developers"
          git rebase upstream/master
          git log -n 3
          cat test
