name: CI test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  MergeTest:
    runs-on: ubuntu-20.04

    steps:
      - name: Source checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Test
        run: |
          git log -n 5
          git branch

      - name: Upstream checkout
        run: |
          git checkout -b source
          git remote add upstream "https://github.com/LNST-project/lnst.git"
          git fetch upstream
          git checkout -b upstream_master upstream/master
          git config --local user.email "lnst-developers@lists.fedorahosted.org"
          git config --local user.name "LNST developers"
          git merge --no-commit --allow-unrelated-histories source